/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KaskadPriceOracle } from "./KaskadPriceOracle";
export * as factories from "./factories";
export { KaskadPriceOracle__factory } from "./factories/KaskadPriceOracle__factory";
