/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface KaskadPriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CIRCUIT_BREAKER_STALENESS"
      | "DECIMALS"
      | "MAX_PRICE_CHANGE_BPS"
      | "MAX_RESUME_CHANGE_BPS"
      | "RESUME_QUORUM_MULTIPLIER"
      | "admin"
      | "assetParams"
      | "currentRound"
      | "expectedPCR0"
      | "getLatestPrice"
      | "getRoundData"
      | "isValidSigner"
      | "latestPrices"
      | "priceHistory"
      | "registerAssets"
      | "registerEnclave"
      | "registeredAssetIds"
      | "signerCount"
      | "updatePrice"
      | "validSigner"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetsRegistered"
      | "EnclaveRegistered"
      | "PriceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CIRCUIT_BREAKER_STALENESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DECIMALS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_PRICE_CHANGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RESUME_CHANGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESUME_QUORUM_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetParams",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRound",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expectedPCR0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundData",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestPrices",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAssets",
    values: [BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEnclave",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredAssetIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CIRCUIT_BREAKER_STALENESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DECIMALS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PRICE_CHANGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_RESUME_CHANGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESUME_QUORUM_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedPCR0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEnclave",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredAssetIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace AssetsRegisteredEvent {
  export type InputTuple = [admin: AddressLike, numAssets: BigNumberish];
  export type OutputTuple = [admin: string, numAssets: bigint];
  export interface OutputObject {
    admin: string;
    numAssets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EnclaveRegisteredEvent {
  export type InputTuple = [
    signer: AddressLike,
    pcr0: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [signer: string, pcr0: string, timestamp: bigint];
  export interface OutputObject {
    signer: string;
    pcr0: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    price: BigNumberish,
    timestamp: BigNumberish,
    numSources: BigNumberish,
    roundId: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    price: bigint,
    timestamp: bigint,
    numSources: bigint,
    roundId: bigint
  ];
  export interface OutputObject {
    assetId: string;
    price: bigint;
    timestamp: bigint;
    numSources: bigint;
    roundId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KaskadPriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): KaskadPriceOracle;
  waitForDeployment(): Promise<this>;

  interface: KaskadPriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CIRCUIT_BREAKER_STALENESS: TypedContractMethod<[], [bigint], "view">;

  DECIMALS: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE_CHANGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_RESUME_CHANGE_BPS: TypedContractMethod<[], [bigint], "view">;

  RESUME_QUORUM_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  assetParams: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  currentRound: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  expectedPCR0: TypedContractMethod<[], [string], "view">;

  getLatestPrice: TypedContractMethod<
    [assetId: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        roundId: bigint;
      }
    ],
    "view"
  >;

  getRoundData: TypedContractMethod<
    [assetId: BytesLike, roundId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
      }
    ],
    "view"
  >;

  isValidSigner: TypedContractMethod<[who: AddressLike], [boolean], "view">;

  latestPrices: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        signedTimestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;

  priceHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        signedTimestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;

  registerAssets: TypedContractMethod<
    [ids: BytesLike[], minSources: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  registerEnclave: TypedContractMethod<
    [attestationDoc: BytesLike],
    [void],
    "nonpayable"
  >;

  registeredAssetIds: TypedContractMethod<[], [string[]], "view">;

  signerCount: TypedContractMethod<[], [bigint], "view">;

  updatePrice: TypedContractMethod<
    [
      assetId: BytesLike,
      price: BigNumberish,
      timestamp: BigNumberish,
      numSources: BigNumberish,
      sourcesHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  validSigner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CIRCUIT_BREAKER_STALENESS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE_CHANGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_RESUME_CHANGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESUME_QUORUM_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetParams"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentRound"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "expectedPCR0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoundData"
  ): TypedContractMethod<
    [assetId: BytesLike, roundId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidSigner"
  ): TypedContractMethod<[who: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "latestPrices"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        signedTimestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        signedTimestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAssets"
  ): TypedContractMethod<
    [ids: BytesLike[], minSources: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEnclave"
  ): TypedContractMethod<[attestationDoc: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredAssetIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "signerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      price: BigNumberish,
      timestamp: BigNumberish,
      numSources: BigNumberish,
      sourcesHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validSigner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssetsRegistered"
  ): TypedContractEvent<
    AssetsRegisteredEvent.InputTuple,
    AssetsRegisteredEvent.OutputTuple,
    AssetsRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EnclaveRegistered"
  ): TypedContractEvent<
    EnclaveRegisteredEvent.InputTuple,
    EnclaveRegisteredEvent.OutputTuple,
    EnclaveRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "AssetsRegistered(address,uint256)": TypedContractEvent<
      AssetsRegisteredEvent.InputTuple,
      AssetsRegisteredEvent.OutputTuple,
      AssetsRegisteredEvent.OutputObject
    >;
    AssetsRegistered: TypedContractEvent<
      AssetsRegisteredEvent.InputTuple,
      AssetsRegisteredEvent.OutputTuple,
      AssetsRegisteredEvent.OutputObject
    >;

    "EnclaveRegistered(address,bytes32,uint256)": TypedContractEvent<
      EnclaveRegisteredEvent.InputTuple,
      EnclaveRegisteredEvent.OutputTuple,
      EnclaveRegisteredEvent.OutputObject
    >;
    EnclaveRegistered: TypedContractEvent<
      EnclaveRegisteredEvent.InputTuple,
      EnclaveRegisteredEvent.OutputTuple,
      EnclaveRegisteredEvent.OutputObject
    >;

    "PriceUpdated(bytes32,uint256,uint256,uint8,uint80)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
