/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface KaskadPriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DECIMALS"
      | "MAX_PRICE_CHANGE_BPS"
      | "MIN_UPDATE_DELAY"
      | "currentRound"
      | "enclave"
      | "expectedPCR0"
      | "getLatestPrice"
      | "getRoundData"
      | "latestPrices"
      | "oracleSigner"
      | "priceHistory"
      | "registerEnclave"
      | "updatePrice"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EnclaveRegistered" | "PriceUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "DECIMALS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_PRICE_CHANGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_UPDATE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRound",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "enclave", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "expectedPCR0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundData",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestPrices",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEnclave",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "DECIMALS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PRICE_CHANGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_UPDATE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enclave", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expectedPCR0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEnclave",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace EnclaveRegisteredEvent {
  export type InputTuple = [
    signer: AddressLike,
    pcr0: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [signer: string, pcr0: string, timestamp: bigint];
  export interface OutputObject {
    signer: string;
    pcr0: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    price: BigNumberish,
    timestamp: BigNumberish,
    numSources: BigNumberish,
    roundId: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    price: bigint,
    timestamp: bigint,
    numSources: bigint,
    roundId: bigint
  ];
  export interface OutputObject {
    assetId: string;
    price: bigint;
    timestamp: bigint;
    numSources: bigint;
    roundId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KaskadPriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): KaskadPriceOracle;
  waitForDeployment(): Promise<this>;

  interface: KaskadPriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DECIMALS: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE_CHANGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_UPDATE_DELAY: TypedContractMethod<[], [bigint], "view">;

  currentRound: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  enclave: TypedContractMethod<
    [],
    [
      [string, bigint, string, boolean] & {
        signer: string;
        registeredAt: bigint;
        pcr0: string;
        active: boolean;
      }
    ],
    "view"
  >;

  expectedPCR0: TypedContractMethod<[], [string], "view">;

  getLatestPrice: TypedContractMethod<
    [assetId: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        roundId: bigint;
      }
    ],
    "view"
  >;

  getRoundData: TypedContractMethod<
    [assetId: BytesLike, roundId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
      }
    ],
    "view"
  >;

  latestPrices: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;

  oracleSigner: TypedContractMethod<[], [string], "view">;

  priceHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;

  registerEnclave: TypedContractMethod<
    [attestationDoc: BytesLike],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [
      assetId: BytesLike,
      price: BigNumberish,
      timestamp: BigNumberish,
      numSources: BigNumberish,
      sourcesHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE_CHANGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_UPDATE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentRound"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "enclave"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, string, boolean] & {
        signer: string;
        registeredAt: bigint;
        pcr0: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "expectedPCR0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoundData"
  ): TypedContractMethod<
    [assetId: BytesLike, roundId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestPrices"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        price: bigint;
        timestamp: bigint;
        numSources: bigint;
        sourcesHash: string;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerEnclave"
  ): TypedContractMethod<[attestationDoc: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      price: BigNumberish,
      timestamp: BigNumberish,
      numSources: BigNumberish,
      sourcesHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EnclaveRegistered"
  ): TypedContractEvent<
    EnclaveRegisteredEvent.InputTuple,
    EnclaveRegisteredEvent.OutputTuple,
    EnclaveRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "EnclaveRegistered(address,bytes32,uint256)": TypedContractEvent<
      EnclaveRegisteredEvent.InputTuple,
      EnclaveRegisteredEvent.OutputTuple,
      EnclaveRegisteredEvent.OutputObject
    >;
    EnclaveRegistered: TypedContractEvent<
      EnclaveRegisteredEvent.InputTuple,
      EnclaveRegisteredEvent.OutputTuple,
      EnclaveRegisteredEvent.OutputObject
    >;

    "PriceUpdated(bytes32,uint256,uint256,uint8,uint80)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
