/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  KaskadPriceOracle,
  KaskadPriceOracleInterface,
} from "../KaskadPriceOracle";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_expectedPCR0",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "_verifier",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DECIMALS",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_PRICE_CHANGE_BPS",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_UPDATE_DELAY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentRound",
    inputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint80",
        internalType: "uint80",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "enclave",
    inputs: [],
    outputs: [
      {
        name: "signer",
        type: "address",
        internalType: "address",
      },
      {
        name: "registeredAt",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "pcr0",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "active",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expectedPCR0",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLatestPrice",
    inputs: [
      {
        name: "assetId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "numSources",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "roundId",
        type: "uint80",
        internalType: "uint80",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundData",
    inputs: [
      {
        name: "assetId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "roundId",
        type: "uint80",
        internalType: "uint80",
      },
    ],
    outputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "numSources",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "latestPrices",
    inputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "numSources",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "sourcesHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "roundId",
        type: "uint80",
        internalType: "uint80",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "oracleSigner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceHistory",
    inputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "",
        type: "uint80",
        internalType: "uint80",
      },
    ],
    outputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "numSources",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "sourcesHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "roundId",
        type: "uint80",
        internalType: "uint80",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerEnclave",
    inputs: [
      {
        name: "attestationDoc",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePrice",
    inputs: [
      {
        name: "assetId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "numSources",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "sourcesHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifier",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IAttestationVerifier",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "EnclaveRegistered",
    inputs: [
      {
        name: "signer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "pcr0",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PriceUpdated",
    inputs: [
      {
        name: "assetId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "price",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "numSources",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "roundId",
        type: "uint80",
        indexed: false,
        internalType: "uint80",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "InsufficientSources",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidAttestation",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidSignature",
    inputs: [],
  },
  {
    type: "error",
    name: "NoEnclaveRegistered",
    inputs: [],
  },
  {
    type: "error",
    name: "PCR0Mismatch",
    inputs: [
      {
        name: "provided",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "expected",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "PriceChangeExceedsLimit",
    inputs: [
      {
        name: "changeBps",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxBps",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "StalePrice",
    inputs: [
      {
        name: "provided",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "current",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "UpdateTooFrequent",
    inputs: [
      {
        name: "elapsed",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minDelay",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
] as const;

export class KaskadPriceOracle__factory {
  static readonly abi = _abi;
  static createInterface(): KaskadPriceOracleInterface {
    return new Interface(_abi) as KaskadPriceOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): KaskadPriceOracle {
    return new Contract(address, _abi, runner) as unknown as KaskadPriceOracle;
  }
}
