use alloy_primitives::{B256, U256};
use eyre::Result;
use k256::ecdsa::SigningKey;
use sha3::{Digest, Keccak256};

/// Trait for signing oracle payloads.
/// MockSigner uses a local private key.
/// EnclaveSigner uses a key generated by NSM/RNG inside the Nitro enclave.
pub trait OracleSigner: Send + Sync {
    /// Sign a 32-byte message digest with EIP-191 (`"\x19Ethereum Signed
    /// Message:\n32" || digest`). Returns the 65-byte (r, s, v) signature
    /// AND the signer's Ethereum address.
    ///
    /// Both price updates and the asset-bundle commitment go through this
    /// one helper so the on-chain contract can use `ECDSA.recover` identically
    /// for either case.
    fn sign_digest(&self, digest: [u8; 32]) -> Result<(Vec<u8>, [u8; 20])>;

    /// Convenience wrapper that assembles the per-price payload, hashes it,
    /// and delegates to `sign_digest`.
    fn sign_price_update(
        &self,
        asset_id: B256,
        price: U256,
        timestamp: u64,
        num_sources: u8,
        sources_hash: B256,
    ) -> Result<(Vec<u8>, [u8; 20])> {
        let mut payload = Vec::with_capacity(32 + 32 + 32 + 1 + 32);
        payload.extend_from_slice(asset_id.as_slice());
        payload.extend_from_slice(&price.to_be_bytes::<32>());
        payload.extend_from_slice(&U256::from(timestamp).to_be_bytes::<32>());
        payload.extend_from_slice(&[num_sources]);
        payload.extend_from_slice(sources_hash.as_slice());
        let digest: [u8; 32] = Keccak256::digest(&payload).into();
        self.sign_digest(digest)
    }

    /// Get the signer's Ethereum address (keccak256 of uncompressed pubkey,
    /// last 20 bytes).
    fn address(&self) -> [u8; 20];

    /// Get the attestation document (if available).
    fn attestation_doc(&self) -> Option<Vec<u8>>;
}

/// Apply the EIP-191 wrapping (`"\x19Ethereum Signed Message:\n32" || digest`),
/// keccak, then sign with the provided key. Returns the 65-byte (r, s, v)
/// signature.
fn sign_eip191(signing_key: &SigningKey, digest: [u8; 32]) -> Result<[u8; 65]> {
    let mut eth_message = Vec::with_capacity(28 + 32);
    eth_message.extend_from_slice(b"\x19Ethereum Signed Message:\n32");
    eth_message.extend_from_slice(&digest);
    let eth_hash: [u8; 32] = Keccak256::digest(&eth_message).into();

    let (signature, recovery_id) = signing_key
        .sign_prehash_recoverable(&eth_hash)
        .map_err(|e| eyre::eyre!("signing failed: {}", e))?;

    let mut out = [0u8; 65];
    out[..64].copy_from_slice(&signature.to_bytes());
    out[64] = recovery_id.to_byte() + 27;
    Ok(out)
}

fn derive_address(signing_key: &SigningKey) -> (Vec<u8>, [u8; 20]) {
    let verifying_key = signing_key.verifying_key();
    let pubkey_bytes = verifying_key.to_encoded_point(false);
    let pubkey_slice = pubkey_bytes.as_bytes();
    let pubkey_uncompressed = &pubkey_slice[1..];
    let hash = Keccak256::digest(pubkey_uncompressed);
    let mut address = [0u8; 20];
    address.copy_from_slice(&hash[12..]);
    (pubkey_slice.to_vec(), address)
}

/// Local signer for development/testing — private key from environment.
pub struct MockSigner {
    signing_key: SigningKey,
    address: [u8; 20],
}

impl MockSigner {
    pub fn new(private_key_hex: &str) -> Result<Self> {
        let key_bytes = hex::decode(private_key_hex.trim_start_matches("0x"))?;
        let signing_key = SigningKey::from_bytes((&key_bytes[..]).into())?;
        let (_pk_bytes, address) = derive_address(&signing_key);
        Ok(Self { signing_key, address })
    }

    /// Generate a random signer for testing.
    pub fn random() -> Self {
        let signing_key = SigningKey::random(&mut rand::thread_rng());
        let (_pk_bytes, address) = derive_address(&signing_key);
        Self { signing_key, address }
    }
}

impl OracleSigner for MockSigner {
    fn sign_digest(&self, digest: [u8; 32]) -> Result<(Vec<u8>, [u8; 20])> {
        let sig = sign_eip191(&self.signing_key, digest)?;
        Ok((sig.to_vec(), self.address))
    }

    fn address(&self) -> [u8; 20] {
        self.address
    }

    fn attestation_doc(&self) -> Option<Vec<u8>> {
        None
    }
}

/// Collect 32 bytes of entropy from NSM `GetRandom`. Each call to the NSM
/// may return fewer bytes than requested — we loop until the buffer is
/// full. Any NSM error bubbles up immediately; we MUST NOT fall back to
/// `thread_rng` here, because that would reintroduce the host-controlled
/// entropy channel we are explicitly avoiding.
#[cfg(target_os = "linux")]
fn nsm_random_seed() -> Result<[u8; 32]> {
    use aws_nitro_enclaves_nsm_api::api::{Request, Response};
    use aws_nitro_enclaves_nsm_api::driver::{nsm_exit, nsm_init, nsm_process_request};

    let fd = nsm_init();
    if fd < 0 {
        return Err(eyre::eyre!("nsm_init failed: {}", fd));
    }

    let mut seed = [0u8; 32];
    let mut filled = 0usize;
    while filled < seed.len() {
        match nsm_process_request(fd, Request::GetRandom) {
            Response::GetRandom { random } => {
                if random.is_empty() {
                    nsm_exit(fd);
                    return Err(eyre::eyre!("NSM GetRandom returned empty buffer"));
                }
                let take = (seed.len() - filled).min(random.len());
                seed[filled..filled + take].copy_from_slice(&random[..take]);
                filled += take;
            }
            Response::Error(e) => {
                nsm_exit(fd);
                return Err(eyre::eyre!("NSM GetRandom error: {:?}", e));
            }
            other => {
                nsm_exit(fd);
                return Err(eyre::eyre!("NSM GetRandom unexpected response: {:?}", other));
            }
        }
    }
    nsm_exit(fd);
    Ok(seed)
}

#[cfg(target_os = "linux")]
pub struct EnclaveSigner {
    signing_key: SigningKey,
    address: [u8; 20],
    /// Uncompressed public key bytes (65 bytes: 0x04 + X + Y).
    pubkey_bytes: Vec<u8>,
}

#[cfg(target_os = "linux")]
impl EnclaveSigner {
    pub fn new() -> Result<Self> {
        // Derive the private key from NSM-provided entropy. `thread_rng` ->
        // guest-kernel CSPRNG, which in a Nitro guest is seeded in part from
        // virtio-rng — a host-controlled channel. A malicious host could
        // bias that pool and make the resulting private key predictable.
        //
        // NSM `GetRandom` is backed directly by the Nitro Security Module —
        // the same hardware component that signs attestation documents. Any
        // attacker who can weaken this entropy source can already forge
        // attestations, so the entropy root is bound to the attestation
        // root.
        let mut seed = nsm_random_seed()?;
        let signing_key = SigningKey::from_bytes((&seed[..]).into())
            .map_err(|e| eyre::eyre!("SigningKey::from_bytes: {}", e))?;
        // Scrub the seed before leaving the stack — `SigningKey::from_bytes`
        // copies the scalar into its own storage, so the buffer is no
        // longer needed.
        use zeroize::Zeroize;
        seed.zeroize();

        let (pubkey_bytes, address) = derive_address(&signing_key);

        let me = Self {
            signing_key,
            address,
            pubkey_bytes,
        };
        // Smoke-test the second NSM code path (attestation) early so the
        // enclave fails fast on a broken NSM instead of at first request.
        me.fresh_attestation_doc()?;
        Ok(me)
    }

    /// Generate a fresh attestation document via NSM. AWS Nitro leaf certs
    /// in the attestation chain live ~3 hours — callers must request a
    /// fresh doc close to when they'll use it on-chain.
    pub fn fresh_attestation_doc(&self) -> Result<Vec<u8>> {
        let fd = aws_nitro_enclaves_nsm_api::driver::nsm_init();
        if fd < 0 {
            return Err(eyre::eyre!("nsm_init failed: {}", fd));
        }

        let request = aws_nitro_enclaves_nsm_api::api::Request::Attestation {
            public_key: Some(self.pubkey_bytes.clone().into()),
            user_data: None,
            nonce: None,
        };

        let response = aws_nitro_enclaves_nsm_api::driver::nsm_process_request(fd, request);
        aws_nitro_enclaves_nsm_api::driver::nsm_exit(fd);

        match response {
            aws_nitro_enclaves_nsm_api::api::Response::Attestation { document } => Ok(document),
            aws_nitro_enclaves_nsm_api::api::Response::Error(err) => {
                Err(eyre::eyre!("NSM Attestation Error: {:?}", err))
            }
            _ => Err(eyre::eyre!("Unexpected NSM response")),
        }
    }
}

#[cfg(target_os = "linux")]
impl OracleSigner for EnclaveSigner {
    fn sign_digest(&self, digest: [u8; 32]) -> Result<(Vec<u8>, [u8; 20])> {
        let sig = sign_eip191(&self.signing_key, digest)?;
        Ok((sig.to_vec(), self.address))
    }

    fn address(&self) -> [u8; 20] {
        self.address
    }

    fn attestation_doc(&self) -> Option<Vec<u8>> {
        match self.fresh_attestation_doc() {
            Ok(doc) => Some(doc),
            Err(e) => {
                tracing::warn!(error = %e, "NSM attestation request failed");
                None
            }
        }
    }
}
